version: 2.1

executors:
  exec:
    docker:
      - image: circleci/golang:1.13
      - image: mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_HOST: 127.0.0.1
jobs:
  go_mod:
    executor: exec
    environment:
      GO111MODULE=on
    steps:
      - checkout
      - run: go mod download
      - run: go mod verify
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - go.mod
            - go.sum

  user_svc_test_and_build:
    executor: exec
    environment:
      GO111MODULE=on
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - run: go test ./cmd/user-svc -v
      - run: go build -v -o ./cmd/user-svc/bin/user-server ./cmd/user-svc
      - persist_to_workspace:
          root: ./cmd/user-svc/bin
          paths: user-server

  book_svc_test_and_build:
    executor: exec
    environment:
      GO111MODULE=on
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - run: go test ./cmd/book-svc -v
      - run: go build -v -o ./cmd/book-svc/bin/book-server ./cmd/book-svc
      - persist_to_workspace:
          root: ./cmd/book-svc/bin
          paths: book-server

  management_svc_test_and_build:
    executor: exec
    environment:
      GO111MODULE=on
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - run: go test ./cmd/management-svc -v
      - run: go build -v -o ./cmd/management-svc/bin/management-server ./cmd/management-svc
      - persist_to_workspace:
          root: ./cmd/management-svc/bin
          paths: management-server

  docker_build:
    executor: exec
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ./cmd/user-svc/bin
      - attach_workspace:
          at: ./cmd/book-svc/bin
      - attach_workspace:
          at: ./cmd/management-svc/bin
      - run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
      - run: docker build -t apstomar/library_user_svc:latest ./cmd/user-svc
      - run: docker push apstomar/library_user_svc:latest
      - run: docker build -t apstomar/library_book_svc:latest ./cmd/book-svc
      - run: docker push apstomar/library_book_svc:latest
      - run: docker build -t apstomar/library_management_svc:latest ./cmd/management-svc
      - run: docker push apstomar/library_management_svc:latest

workflows:
  version: 2.1
  go_tests:
    jobs:
      - go_mod
      - user_svc_test_and_build:
          requires:
            - go_mod
      - book_svc_test_and_build:
          requires:
             - go_mod
      - management_svc_test_and_build:
          requires:
            - go_mod

      - docker_build:
          requires:
            - user_svc_test_and_build
            - book_svc_test_and_build
            - management_svc_test_and_build
          filters:
            branches:
              only: master