apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: library-es
spec:
  ports:
    - port: 9200
      protocol: TCP
  selector:
    app: library-es

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: library-es
spec:
  selector:
    matchLabels:
      app: library-es
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: library-es
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
              name: elasticsearch
              protocol: TCP
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 500m
