apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: library-kibana
spec:
  ports:
    - port: 5601
      protocol: TCP
  selector:
    app: library-kibana

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: library-kibana
spec:
  selector:
    matchLabels:
      app: library-kibana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: library-kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana-oss:6.4.2
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200
          ports:
            - containerPort: 5601
              protocol: TCP
