apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: library-database
spec:
  ports:
    - port: 3306
  selector:
    app: library-database

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: library-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: library-database
spec:
  selector:
    matchLabels:
      app: library-database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: library-database
    spec:
      containers:
        - image: mysql
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: library-secret
                  key: sql_password
            - name: MYSQL_DATABASE
              value: library
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc