apiVersion: v1
kind: Secret
metadata:
  name: library-secret
type: Opaque
data:
  jwt_signing_key: c2VjcmV0
  sql_password: cGFzc3dvcmQ=
  sql_url: cm9vdDpwYXNzd29yZEB0Y3AobXlzcWw6MzMwNikvbGlicmFyeT9jaGFyc2V0PXV0ZjgmcGFyc2VUaW1lPVRydWUmbG9jPUxvY2Fs